name: Create Astarte Cluster

on:
  push:
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create Astarte Cluster
        id: astarte
        uses: astarte-platform/astarte-cluster-action@v1
      - name: test
        run: | 
          echo "${{steps.astarte.outputs.housekeeping_key}}"
          echo "${{steps.astarte.outputs.realm_key}}"
          astartectl cluster show