name: Create Astarte Cluster

on:
  push:
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create Astarte Cluster
        id: astarte
        uses: astarte-platform/astarte-cluster-action@v1
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: ls
        run: ls
      - name: test
        run: | 
          astartectl appengine devices list
          astartectl realm-management interfaces install $GITHUB_WORKSPACE/examples/interfaces/com.test.Everything.json
          astartectl realm-management interfaces ls
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example simple