name: Create Astarte Cluster

on:
  push:
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create Astarte Cluster
        id: astarte
        uses: astarte-platform/astarte-cluster-action@v1
      - name: test
        run: | 
          echo "${{steps.astarte.outputs.housekeeping_key}}"
          echo "${{steps.astarte.outputs.realm_key}}" > /tmp/realmkey.crt.pem
          astartectl appengine devices list --realm-name "test" -k "/tmp/realmkey.crt.pem" --astarte-url "https://api.autotest.astarte-platform.org"

      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example simple